import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import '../models/promotion.dart';
import '../theme/candy_colors.dart';

// Auto-generated from assets/logos/ — regenerate when new logos are added.
const _kLocalLogoDomains = <String>{
  '1800petmeds.com',
  '24s.com',
  'abercrombie.com',
  'acehardware.com',
  'acer.com',
  'adidas.com',
  'adorama.com',
  'adoreme.com',
  'advanceautoparts.com',
  'ae.com',
  'aesop.com',
  'alamo.com',
  'albertsons.com',
  'aldi.us',
  'aldoshoes.com',
  'algreens.com',
  'aliceandolivia.com',
  'allsaints.com',
  'almart.com',
  'aloyoga.com',
  'altuzarra.com',
  'amazon.com',
  'amctheatres.com',
  'amiparis.com',
  'analuisa.com',
  'aninebing.com',
  'anker.com',
  'anntaylor.com',
  'anthropologie.com',
  'apc-us.com',
  'apple.com',
  'applebees.com',
  'appliancesconnection.com',
  'arbys.com',
  'aritzia.com',
  'arlo.com',
  'article.com',
  'ashleyfurniture.com',
  'asics.com',
  'asos.com',
  'asus.com',
  'athleta.gap.com',
  'athome.com',
  'audio-technica.com',
  'augustinusbader.com',
  'autozone.com',
  'avis.com',
  'avocadogreenmattress.com',
  'awaytravel.com',
  'ayfair.com',
  'babylist.com',
  'balenciaga.com',
  'bananarepublic.gap.com',
  'bandier.com',
  'bang-olufsen.com',
  'bark.co',
  'baskinrobbins.com',
  'bathandbodyworks.com',
  'bcbg.com',
  'beallsflorida.com',
  'bedbathandbeyond.com',
  'behr.com',
  'belk.com',
  'belkin.com',
  'benefitcosmetics.com',
  'benihana.com',
  'benjaminmoore.com',
  'benq.com',
  'bestbuy.com',
  'biglots.com',
  'bigotires.com',
  'bioliteenergy.com',
  'birdies.com',
  'bjs.com',
  'blackanddecker.com',
  'blackrockcoffee.com',
  'bloomingdales.com',
  'bludot.com',
  'bluebuffalo.com',
  'bluemercury.com',
  'bluenile.com',
  'bodi.com',
  'bodybuilding.com',
  'bogner.com',
  'bollandbranch.com',
  'boohoo.com',
  'booking.com',
  'bosch-home.com',
  'boschtools.com',
  'bose.com',
  'bowerswilkins.com',
  'bowflex.com',
  'bowlero.com',
  'boxlunch.com',
  'briggs-riley.com',
  'brilliantearth.com',
  'brooklinen.com',
  'brooksbrothers.com',
  'brooksrunning.com',
  'budget.com',
  'buffalowildwings.com',
  'build.com',
  'burlington.com',
  'burrow.com',
  'calvinklein.us',
  'canon.com',
  'cariboucoffee.com',
  'carters.com',
  'cartier.com',
  'casper.com',
  'castlery.com',
  'cb2.com',
  'champssports.com',
  'chewy.com',
  'chick-fil-a.com',
  'chicos.com',
  'chilis.com',
  'chipotle.com',
  'choicehotels.com',
  'chopard.com',
  'christianlouboutin.com',
  'christopheresber.com.au',
  'churchs.com',
  'cinemark.com',
  'clarks.com',
  'clubmonaco.com',
  'coach.com',
  'colehaan.com',
  'colourpop.com',
  'columbia.com',
  'containerstore.com',
  'converse.com',
  'corsair.com',
  'cos.com',
  'costco.com',
  'crackerbarrel.com',
  'craftsman.com',
  'crateandbarrel.com',
  'cremedelamer.com',
  'crocs.com',
  'culvers.com',
  'cuyana.com',
  'cvs.com',
  'danielwellington.com',
  'deere.com',
  'dell.com',
  'delta.com',
  'deltaco.com',
  'demellierlondon.com',
  'dennys.com',
  'denon.com',
  'dermstore.com',
  'dewalt.com',
  'dillards.com',
  'diptyqueparis.com',
  'direct.playstation.com',
  'discounttire.com',
  'disneyplus.com',
  'dji.com',
  'dollargeneral.com',
  'dollarshaveclub.com',
  'dollywood.com',
  'dominos.com',
  'doona.com',
  'dossier.co',
  'drinkag1.com',
  'drmartens.com',
  'drunkelephant.com',
  'dsw.com',
  'duluthtrading.com',
  'dunkindonuts.com',
  'dutchbros.com',
  'dvf.com',
  'dwr.com',
  'dxracer.com',
  'dyson.com',
  'ecoflow.com',
  'eddiebauer.com',
  'egmans.com',
  'eightwatchers.com',
  'einsteinbros.com',
  'electronics.sony.com',
  'elfcosmetics.com',
  'eloquii.com',
  'endys.com',
  'enterprise.com',
  'epicgames.com',
  'estelm.com',
  'esterndigital.com',
  'ethanallen.com',
  'etro.com',
  'everlane.com',
  'express.com',
  'extendedstayamerica.com',
  'exxon.com',
  'factor75.com',
  'fairmont.com',
  'famousfootwear.com',
  'fandango.com',
  'farfetch.com',
  'farmrio.com',
  'fashionnova.com',
  'fashionphile.com',
  'fearofgod.com',
  'fentybeauty.com',
  'finishline.com',
  'firehousesubs.com',
  'firestonecompleteautocare.com',
  'fivebelow.com',
  'fiveguys.com',
  'flooranddecor.com',
  'flyfrontier.com',
  'food4less.com',
  'foodlion.com',
  'footlocker.com',
  'forever21.com',
  'fossil.com',
  'fourseasons.com',
  'freepeople.com',
  'fuelrewards.com',
  'functionofbeauty.com',
  'funko.com',
  'furbo.com',
  'gainful.com',
  'gamestop.com',
  'ganni.com',
  'gap.com',
  'gardenoflife.com',
  'garmin.com',
  'gianteagle.com',
  'giantfood.com',
  'gianvitorossi.com',
  'givenchy.com',
  'gloriousgaming.com',
  'glossier.com',
  'goalzero.com',
  'goat.com',
  'gog.com',
  'goldengoose.com',
  'goli.com',
  'google.com',
  'gorjana.com',
  'grailed.com',
  'greatwolf.com',
  'greenchef.com',
  'greenmangaming.com',
  'gucci.com',
  'guess.com',
  'hannaandersson.com',
  'harborfreight.com',
  'harristeeter.com',
  'hasbro.com',
  'hasbropulse.com',
  'hataburger.com',
  'headspace.com',
  'heb.com',
  'hermanmiller.com',
  'hexclad.com',
  'heyharper.com',
  'hillspet.com',
  'hilton.com',
  'hitehouseblackmarket.com',
  'hm.com',
  'hoka.com',
  'holefoodsmarket.com',
  'hollisterco.com',
  'homedepot.com',
  'homegoods.com',
  'hopper.com',
  'hotels.com',
  'hottopic.com',
  'hp.com',
  'hulu.com',
  'humblebundle.com',
  'hungryroot.com',
  'hyperx.com',
  'hy-vee.com',
  'iherb.com',
  'ihg.com',
  'ihop.com',
  'ikea.com',
  'illiams-sonoma.com',
  'ilmakiage.com',
  'incofoods.com',
  'indsorstore.com',
  'ingles-markets.com',
  'ingstop.com',
  'jackery.com',
  'jackinthebox.com',
  'jamba.com',
  'jbl.com',
  'jcpenney.com',
  'jcrew.com',
  'jdsports.com',
  'jerseymikes.com',
  'jetblue.com',
  'jewelosco.com',
  'jiffylube.com',
  'jimmyjohns.com',
  'johnstonmurphy.com',
  'jomalone.com',
  'journeys.com',
  'joybird.com',
  'katespade.com',
  'kef.com',
  'kendrascott.com',
  'kiehls.com',
  'kizik.com',
  'klipsch.com',
  'kohls.com',
  'koio.co',
  'krispykreme.com',
  'kroger.com',
  'kyliecosmetics.com',
  'lagence.com',
  'landsend.com',
  'lanebryant.com',
  'larroude.com',
  'la-z-boy.com',
  'lecreuset.com',
  'lee.com',
  'lelabofragrances.com',
  'lemaire.fr',
  'lenovo.com',
  'lesschwab.com',
  'lg.com',
  'lidl.com',
  'lifeextension.com',
  'lillypulitzer.com',
  'littlecaesars.com',
  'livemomentous.com',
  'llbean.com',
  'loft.com',
  'logitech.com',
  'logitechg.com',
  'longchamp.com',
  'longhornsteakhouse.com',
  'lovesac.com',
  'lovevery.com',
  'luckybrand.com',
  'luckysupermarkets.com',
  'lululemon.com',
  'macys.com',
  'madewell.com',
  'mainevent.com',
  'maisonkitsune.com',
  'maisonmargiela-fragrances.us',
  'maje.com',
  'makitatools.com',
  'manoloblahnik.com',
  'manscaped.com',
  'mansurgavriel.com',
  'marchesa.com',
  'margauxny.com',
  'marianos.com',
  'marriott.com',
  'marshalls.com',
  'massimodutti.com',
  'mattel.com',
  'mavistire.com',
  'max.com',
  'maytag.com',
  'mcdonalds.com',
  'meijer.com',
  'mejuri.com',
  'melissaanddoug.com',
  'merrell.com',
  'messika.com',
  'michaelkors.com',
  'microcenter.com',
  'microsoft.com',
  'midas.com',
  'mikimotoamerica.com',
  'milkmakeup.com',
  'milwaukeetool.com',
  'misfitsmarket.com',
  'modaoperandi.com',
  'modcloth.com',
  'moes.com',
  'moncler.com',
  'monicavinader.com',
  'monro.com',
  'morphe.com',
  'msi.com',
  'mugler.com',
  'myprotein.com',
  'mytheresa.com',
  'mzwallace.com',
  'napaonline.com',
  'nastygal.com',
  'nationalcar.com',
  'naturalizer.com',
  'necessaire.com',
  'nemoequipment.com',
  'nespresso.com',
  'net-a-porter.com',
  'newegg.com',
  'nike.com',
  'nikonusa.com',
  'ninewest.com',
  'nintendo.com',
  'nomnomnow.com',
  'noodles.com',
  'nordictrack.com',
  'nordstrom.com',
  'nordstromrack.com',
  'northerntool.com',
  'nowfoods.com',
  'nunababy.com',
  'nurx.com',
  'nylabone.com',
  'nyxcosmetics.com',
  'nzxt.com',
  'off---white.com',
  'olivegarden.com',
  'ollie.com',
  'on.com',
  'onepeloton.com',
  'optimumnutrition.com',
  'oreillyauto.com',
  'orldmarket.com',
  'osprey.com',
  'ouraring.com',
  'outback.com',
  'overstock.com',
  'pacsun.com',
  'pandaexpress.com',
  'panerabread.com',
  'parachutehome.com',
  'paramountplus.com',
  'patagonia.com',
  'patmcgrath.com',
  'peacocktv.com',
  'peakdesign.com',
  'peets.com',
  'pepboys.com',
  'petco.com',
  'petsafe.com',
  'petsmart.com',
  'pfchangs.com',
  'pinstripes.com',
  'pizzahut.com',
  'playstation.com',
  'pomellato.com',
  'potterybarn.com',
  'potterybarnkids.com',
  'powera.com',
  'prada.com',
  'prettylittlething.us',
  'pricechopper.com',
  'princesspolly.com',
  'prose.com',
  'publiclands.com',
  'publix.com',
  'puma.com',
  'purina.com',
  'purple.com',
  'qdoba.com',
  'quiksilver.com',
  'rackroomshoes.com',
  'rag-bone.com',
  'rainbowshops.com',
  'ralphlauren.com',
  'ralphs.com',
  'rangler.com',
  'rarebeauty.com',
  'razer.com',
  'rebag.com',
  'rebeccaminkoff.com',
  'redrobin.com',
  'reebok.com',
  'regmovies.com',
  'rei.com',
  'reiss.com',
  'repfitness.com',
  'revivalrugs.com',
  'revolve.com',
  'ridgid.com',
  'rimowa.com',
  'riteaid.com',
  'ritual.com',
  'ritzcarlton.com',
  'ro.co',
  'roborock.com',
  'rockler.com',
  'roomstogo.com',
  'rothys.com',
  'roxy.com',
  'ryobitools.com',
  'saatva.com',
  'safeway.com',
  'saksoff5th.com',
  'sallybeauty.com',
  'samedelman.com',
  'samsclub.com',
  'samsonite.com',
  'samsung.com',
  'sandro-paris.com',
  'sarahflint.com',
  'saucony.com',
  'savemart.com',
  'secretlab.co',
  'self-portrait.com',
  'sennheiser-hearing.com',
  'sephora.com',
  'shakeshack.com',
  'shein.com',
  'sherwin-williams.com',
  'shoecarnival.com',
  'shopcider.com',
  'shoprite.com',
  'shopus.furbo.com',
  'showpo.com',
  'sixflags.com',
  'skechers.com',
  'skinceuticals.com',
  'skinstore.com',
  'skyzone.com',
  'soldejaneiro.com',
  'sonicdrivein.com',
  'sonos.com',
  'sony.com',
  'southwest.com',
  'spacenk.com',
  'sperry.com',
  'spotify.com',
  'sprouts.com',
  'starbucks.com',
  'staud.clothing',
  'steampowered.com',
  'steelseries.com',
  'stevemadden.com',
  'stihlusa.com',
  'stoneisland.com',
  'stopandshop.com',
  'stories.com',
  'strathberry.com',
  'stuartweitzman.com',
  'subway.com',
  'subzero-wolf.com',
  'sundayriley.com',
  'surlatable.com',
  'swansonvitamins.com',
  'sweetgreen.com',
  'tacobell.com',
  'take5.com',
  'talbots.com',
  'target.com',
  'tartecosmetics.com',
  'tatcha.com',
  'tedbaker.com',
  'tempurpedic.com',
  'the-citizenry.com',
  'thefarmersdog.com',
  'thefreshmarket.com',
  'thenorthface.com',
  'theory.com',
  'therabody.com',
  'therealreal.com',
  'thredup.com',
  'thrivemarket.com',
  'tibi.com',
  'tillys.com',
  'tirerack.com',
  'tjmaxx.tjx.com',
  'tjx.com',
  'tommy.com',
  'toofaced.com',
  'topgolf.com',
  'toro.com',
  'torrid.com',
  'toryburch.com',
  'tractorsupply.com',
  'traderjoes.com',
  'transparentlabs.com',
  'travelpro.com',
  'tropicalsmoothiecafe.com',
  'truevalue.com',
  'tuftandneedle.com',
  'tumi.com',
  'turtlebeach.com',
  'ugg.com',
  'ulta.com',
  'underarmour.com',
  'universalstudioshollywood.com',
  'uppababy.com',
  'urbandecay.com',
  'urbanoutfitters.com',
  'usa.canon.com',
  'usa.tommy.com',
  'valvoline.com',
  'vancleefarpels.com',
  'vans.com',
  'verabradley.com',
  'vestiairecollective.com',
  'vince.com',
  'vineyardvines.com',
  'vitaminshoppe.com',
  'volcom.com',
  'vrbo.com',
  'walgreens.com',
  'walmart.com',
  'wayfair.com',
  'weber.com',
  'wegmans.com',
  'weightwatchers.com',
  'wendys.com',
  'westelm.com',
  'westerndigital.com',
  'whataburger.com',
  'whatgoesaroundnyc.com',
  'whirlpool.com',
  'whitehouseblackmarket.com',
  'williams-sonoma.com',
  'wincofoods.com',
  'windsorstore.com',
  'wingstop.com',
  'worldmarket.com',
  'wrangler.com',
  'wyndhamhotels.com',
  'xbox.com',
  'yndhamhotels.com',
  'zara.com',
  'zestypaws.com',
  'zumiez.com',
};

class BrandLogo extends StatefulWidget {
  final Promotion promo;
  final double size;

  const BrandLogo({super.key, required this.promo, this.size = 40});

  @override
  State<BrandLogo> createState() => _BrandLogoState();
}

class _BrandLogoState extends State<BrandLogo> {
  // For network-only brands: 0=icon.horse, 1=google favicon, 2=initials
  int _networkAttempt = 0;

  String get _initials {
    final words = widget.promo.brand.trim().split(RegExp(r'\s+'));
    if (words.length >= 2) return (words[0][0] + words[1][0]).toUpperCase();
    return widget.promo.brand
        .substring(0, widget.promo.brand.length.clamp(0, 2))
        .toUpperCase();
  }

  Color get _avatarColor {
    const colors = [
      Candy.raspberry,
      Candy.mint,
      Candy.lavender,
      Candy.pink,
      Color(0xFF1565C0),
      Color(0xFFE65100),
      Candy.raspberry,
      Candy.lavender,
    ];
    return colors[widget.promo.brand.hashCode.abs() % colors.length];
  }

  Widget _initialsWidget() {
    final size = widget.size;
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: _avatarColor.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(size * 0.25),
      ),
      child: Center(
        child: Text(
          _initials,
          style: TextStyle(
            color: _avatarColor,
            fontWeight: FontWeight.w700,
            fontSize: size * 0.35,
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final domain = widget.promo.rootDomain;
    final size = widget.size;

    if (domain == null) return _initialsWidget();

    // Local asset: synchronous check, no shimmer
    if (_kLocalLogoDomains.contains(domain)) {
      return ClipRRect(
        borderRadius: BorderRadius.circular(size * 0.25),
        child: Image.asset(
          'assets/logos/$domain.png',
          width: size,
          height: size,
          fit: BoxFit.contain,
          errorBuilder: (_, _, _) => _initialsWidget(),
        ),
      );
    }

    // Network: CachedNetworkImage so repeat views are instant from disk cache
    if (_networkAttempt >= 2) return _initialsWidget();

    final url = _networkAttempt == 0
        ? 'https://icon.horse/icon/$domain'
        : 'https://www.google.com/s2/favicons?domain=$domain&sz=128';

    return ClipRRect(
      borderRadius: BorderRadius.circular(size * 0.25),
      child: CachedNetworkImage(
        imageUrl: url,
        width: size,
        height: size,
        fit: BoxFit.contain,
        fadeInDuration: const Duration(milliseconds: 150),
        placeholder: (_, _) => _initialsWidget(),
        errorWidget: (_, _, _) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (mounted) setState(() => _networkAttempt++);
          });
          return _initialsWidget();
        },
      ),
    );
  }
}
